/* R-specific part of the Fields2Cover SWIG interface.
 *
 * SWIG's R backend generates S4 classes plus `$`-dispatched methods and
 * reuses the __getitem__ / __setitem__ / __str__ protocol, so almost the whole
 * interface is shared with Python. Only the differences live here.
 */

/* R's std_vector.i converts std::vector of primitives to and from native
 * atomic vectors, so the wrapper classes instantiated for Python are both
 * unnecessary and broken here (their constructors return a bare externalptr).
 * They are skipped in swig/Fields2Cover.i under #if !defined(SWIGR). */

%include "magic_methods.i"

/* Note for maintainers: operator overloads are exported by SWIG's R backend
 * under textual names (Plus, Minus, Multiply, Divide, EqualEqual, NotEqual,
 * LessThan), not as R's S4 group generics. Mapping them to `+`, `-`, `==`
 * would need explicit setMethod() calls in the R package layer; see
 * swig/r/fixups.R for where such code belongs.
 *
 * Scoped enums (`enum class`) are mis-generated by SWIG 4.4.0's R backend;
 * swig/r/fixups.R repairs the enumeration tables at load time. */
